server:
  port: 8300
# 关闭安全认证,否则actuator提供的url访问报错401,例如:/refresh或/evn等.  
management:
  security:
    enabled: false  
spring:
  # java -D属性可以覆盖本远程参数
  cloud:
    config:
      overrideSystemProperties: false
  # 和spring-cloud-starter-bus-amqp配合,用于/bus/refresh分布式服务属性刷新
  rabbitmq:
    host: 192.168.5.29
    port: 5672
    username: admin
    password: Rabbitmq-401    
  # devtools
  devtools: 
    restart: 
      enabled: false    
# eureka客户端    
eureka:
  client:
    service-url:
      # 基于Basic的Security的访问eureka服务器
      defaultZone: http://sc-eureka:veDSJeUX-JSxkWrk@192.168.5.78:8070/eureka/,http://sc-eureka:veDSJeUX-JSxkWrk@192.168.5.78:8071/eureka/
    # 客户端监控检查(定时检查并发送健康状态到eureka服务器)  
    healthcheck:
      enabled: true
  instance:
    # 基于ip地址注册到eureka         
    prefer-ip-address: true     
# 日志    
logging:
  level:
    root: INFO    
# hystrix 启动并发策略(自定义属性)
hystrix: 
  concurrent_strategy:  
    enabled: true
  command: 
    SampleServiceFeignClient#findByIdWithSleep(Long,Long): 
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000   
feign: 
  httpclient: 
    # 使用apache httpclient
    enabled: true    
  hystrix:  
    # 开启hystrix+feign  
    enabled: true   
 
