server:
  port: 8090
# 关闭安全认证,否则actuator提供的url访问报错401,例如:/refresh或/evn等.  
management:
  security:
    enabled: false    
spring:
  # java -D属性可以覆盖本远程参数
  cloud:
    config:
      overrideSystemProperties: false
  # 和spring-cloud-starter-bus-amqp配合,用于/bus/refresh分布式服务属性刷新
  rabbitmq:
    host: 192.168.5.29
    port: 5672
    username: admin
    password: Rabbitmq-401
  http:   
    multipart: 
      # 整个请求大小限制(1个请求可能包括多个上传文件)
      max-request-size: 20Mb
      # 单个文件大小限制
      max-file-size: 10Mb    
  # devtools
  devtools: 
    restart: 
      enabled: false    
# eureka客户端    
eureka:
  client:
    service-url:
      # 基于Basic的Security的访问eureka服务器
      defaultZone: http://sc-eureka:veDSJeUX-JSxkWrk@192.168.5.78:8070/eureka/,http://sc-eureka:veDSJeUX-JSxkWrk@192.168.5.78:8071/eureka/
    # 客户端监控检查(定时检查并发送健康状态到eureka服务器)  
    healthcheck:
      enabled: true
  instance:
    # 基于ip地址注册到eureka         
    prefer-ip-address: true            
# 日志    
logging:
  level:
    root: INFO 
# 配置zuul->ribbon->使用APACHE HTTP Client
ribbon: 
  restclient:  
    enabled: true
# 配置zuul
zuul: 
  # 忽略所有的服务
  ignored-services: '*' 
  # 指定请求前缀
  prefix: /api
  # 转发请求到服务时,是否去掉prefix前缀字符
  strip-prefix: true
  # 开放服务
  routes: 
    sc-sampleservice: 
      path: /sampleservice/** 
      sensitive-headers: Cookie,Set-Cookie,Authorization

