server:
  port: 6001
# 关闭安全认证,否则actuator提供的url访问报错401,例如:/refresh或/evn等.  
management:
  security:
    enabled: false    
spring:
  # java -D属性可以覆盖本远程参数
  cloud:
    config:
      overrideSystemProperties: false
  # 和spring-cloud-starter-bus-amqp配合,用于/bus/refresh分布式服务属性刷新
  rabbitmq:
    host: 192.168.5.29
    port: 5672
    username: admin
    password: Rabbitmq-401    
  # devtools
  devtools: 
    restart: 
      enabled: false    
  # spring jpa
  jpa:
    database: ORACLE
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
  # datasource
  datasource:
    platform: oracle
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//192.168.5.36:1521/dyitdb
    username: teps
    password: data
    dbcp2:
      test-while-idle: true
      validation-query: select 1 from dual   
  # redis      
  redis:
    host: 192.168.5.36
    port: 6379
    database: 10
    #password: 
    timeout: 1000
    pool:
      min-idle: 1
      max-idle: 1
      max-active: 100
      max-wait: 1000      
# eureka客户端    
eureka:
  client:
    service-url:
      # 基于Basic的Security的访问eureka服务器
      defaultZone: http://dy-eureka:WEJa2w-LHrZKH@192.168.5.78:8070/eureka/
    # 客户端监控检查(定时检查并发送健康状态到eureka服务器)  
    healthcheck:
      enabled: true
  instance:
    # 基于ip地址注册到eureka         
    prefer-ip-address: true     
# 日志    
logging:
  level:
    root: INFO    
    org.springframework.jdbc: trace
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.security.web.authentication: debug
# oauth2 Edgware 版本有bug，因此需要下面的配置把认证过滤器提前
security:
  oauth2:
    resource:
      filter-order: 3    
