server:
  port: 9600
# 关闭安全认证,否则actuator提供的url访问报错401,例如:/refresh或/evn等.  
management:
  security:
    enabled: false  
spring:
  cloud:
    config:
      # java -D属性可以覆盖本远程参数
      overrideSystemProperties: false
    alibaba: 
      seata: 
        tx-service-group: sc-seata-test-fescar-service-group
  # 和spring-cloud-starter-bus-amqp配合,用于/bus/refresh分布式服务属性刷新
  rabbitmq:
    host: 192.168.5.29
    port: 5672
    username: admin
    password: Rabbitmq-401    
  # spring jpa
  jpa:
    database: ORACLE
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
  # datasource
  datasource:
    platform: oracle
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//192.168.5.36:1521/dyitdb
    username: seata1
    password: data
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      test-while-idle: true
      validation-query: select 1 from dual
      default-auto-commit: false
  devtools:
    restart:
      enabled: false    
# eureka客户端    
eureka:
  client:
    service-url:
      # 基于Basic的Security的访问eureka服务器
      defaultZone: http://sc-eureka:veDSJeUX-JSxkWrk@192.168.5.78:8070/eureka/,http://sc-eureka:veDSJeUX-JSxkWrk@192.168.5.78:8071/eureka/
    # 客户端监控检查(定时检查并发送健康状态到eureka服务器)  
    healthcheck:
      enabled: true
  instance:
    # 基于ip地址注册到eureka         
    prefer-ip-address: true     
# 日志    
logging:
  level:
    root: INFO    
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE   
    io.seata: DEBUG
